swagger: "2.0"
info:
  title: rest api - user
  version: 1.0.0
tags:
  - name: UserService
host: localhost:8081
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/v1/user/get/{id}:
    get:
      summary: Endpoint untuk get user bedasarkan id
      description: Masukkan uuid yang valid
      operationId: UserService_GetUser
      responses:
        "200":
          description: contoh response, 200 ketika ...
          schema:
            $ref: '#/definitions/userUserResponse'
        "400":
          description: contoh response, 400 ketika ...
          schema: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          description: uuid
          in: path
          required: true
          type: string
          format: string
        - name: name
          in: query
          required: false
          type: string
        - name: occupation
          in: query
          required: false
          type: string
        - name: email
          in: query
          required: false
          type: string
        - name: password_hash
          in: query
          required: false
          type: string
        - name: avatar_file_name
          in: query
          required: false
          type: string
        - name: role
          in: query
          required: false
          type: string
        - name: created_at
          in: query
          required: false
          type: string
        - name: updated_at
          in: query
          required: false
          type: string
      tags:
        - UserService
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  userUserResponse:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      occupation:
        type: string
      email:
        type: string
      password_hash:
        type: string
      avatar_file_name:
        type: string
      role:
        type: string
      created_at:
        type: string
      updated_at:
        type: string
